# Generated by Django 4.2.3 on 2024-10-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_url', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlinfo',
            name='slug',
        ),
        migrations.AddField(
            model_name='urlinfo',
            name='short_url',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
    ]
