# Generated by Django 4.2.3 on 2024-10-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_url', '0002_remove_urlinfo_slug_urlinfo_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlinfo',
            name='slug',
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
    ]
