# Generated by Django 4.2.3 on 2024-10-05 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_url', '0003_urlinfo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlinfo',
            name='slug',
        ),
    ]
