# Generated by Django 4.2.3 on 2024-10-06 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_url', '0004_remove_urlinfo_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=500)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='urlinfo',
            name='user',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='urlinfo',
            name='short_url',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='urlinfo',
            name='url',
            field=models.URLField(max_length=1000, unique=True),
        ),
    ]
