# Generated by Django 4.2.3 on 2024-10-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_url', '0007_urlinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='email',
        ),
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
