# Generated by Django 4.2.3 on 2024-10-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_url', '0009_alter_urlinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlinfo',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
